"""Indice unico para aviso pendente por produto

Revision ID: 15ebb61108b1
Revises: 54fe0f0e2afb
Create Date: 2026-09-09 21:17:01.087988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ebb61108b1'
down_revision = '54fe0f0e2afb'
branch_labels = None
depends_on = None


def upgrade():
    # Um banco que ja' rodou com a corrida pode ter avisos pendentes repetidos;
    # sem limpar antes, a criacao do indice unico falha e o deploy para. Mantem
    # o mais recente de cada par (produto, tipo) e resolve os demais.
    op.execute("""
        UPDATE alerta SET status = 'resolvido', resolvido_em = NOW()
        WHERE status = 'pendente' AND id NOT IN (
            SELECT max(id) FROM alerta WHERE status = 'pendente'
            GROUP BY produto_id, tipo
        )
    """)

    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.create_index('uq_alerta_pendente_por_produto', ['produto_id', 'tipo'], unique=True, postgresql_where=sa.text("status = 'pendente'"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_index('uq_alerta_pendente_por_produto', postgresql_where=sa.text("status = 'pendente'"))

    # ### end Alembic commands ###
