"""Estrutura inicial do controle de estoque

Revision ID: 1aae989e9c24
Revises: 
Create Date: 2026-08-29 03:08:23.445008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Tipos ENUM do Postgres criados junto com as tabelas (ver upgrade()). O
# Alembic nao remove ENUMs sozinho no downgrade, entao isso e' feito na mao
# no fim de downgrade() - senao um downgrade seguido de upgrade falha com
# "type ... already exists".
_ENUMS = ['papel_usuario', 'categoria_produto', 'tipo_alerta', 'status_alerta',
          'tipo_movimento', 'motivo_perda']


# revision identifiers, used by Alembic.
revision = '1aae989e9c24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_especial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dia_especial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dia_especial_data'), ['data'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'operador', 'repositor', name='papel_usuario'), nullable=False),
    sa.Column('contato_telegram', sa.String(length=60), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_login'), ['login'], unique=True)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.Enum('perecivel', 'nao_perecivel', name='categoria_produto'), nullable=False),
    sa.Column('setor', sa.String(length=60), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('limite_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('limite_minimo_fim_de_semana', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('dias_aviso_validade', sa.Integer(), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('responsavel_padrao_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_padrao_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_produto_nome')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_setor'), ['setor'], unique=False)

    op.create_table('alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('limite_minimo', 'validade_proxima', 'parado_perecivel', name='tipo_alerta'), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'resolvido', name='status_alerta'), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('enviado_telegram', sa.Boolean(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerta_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerta_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerta_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerta_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerta_tipo'), ['tipo'], unique=False)

    op.create_table('lista_compra_sugerida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_sugerida', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('data_geracao', sa.Date(), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=False),
    sa.Column('comprado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'data_geracao', name='uq_sugestao_produto_dia')
    )
    with op.batch_alter_table('lista_compra_sugerida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lista_compra_sugerida_data_geracao'), ['data_geracao'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_compra_sugerida_produto_id'), ['produto_id'], unique=False)

    op.create_table('lote_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantidade_inicial', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('origem_compra', sa.String(length=120), nullable=True),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lote_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lote_estoque_data_entrada'), ['data_entrada'], unique=False)
        batch_op.create_index(batch_op.f('ix_lote_estoque_data_validade'), ['data_validade'], unique=False)
        batch_op.create_index(batch_op.f('ix_lote_estoque_produto_id'), ['produto_id'], unique=False)

    op.create_table('movimento_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('entrada', 'saida', 'perda', name='tipo_movimento'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('vencido', 'estragado', 'danificado', name='motivo_perda'), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimento_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimento_estoque_data_hora'), ['data_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_estoque_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_estoque_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimento_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimento_estoque_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimento_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimento_estoque_data_hora'))

    op.drop_table('movimento_estoque')
    with op.batch_alter_table('lote_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lote_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_lote_estoque_data_validade'))
        batch_op.drop_index(batch_op.f('ix_lote_estoque_data_entrada'))

    op.drop_table('lote_estoque')
    with op.batch_alter_table('lista_compra_sugerida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lista_compra_sugerida_produto_id'))
        batch_op.drop_index(batch_op.f('ix_lista_compra_sugerida_data_geracao'))

    op.drop_table('lista_compra_sugerida')
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerta_tipo'))
        batch_op.drop_index(batch_op.f('ix_alerta_status'))
        batch_op.drop_index(batch_op.f('ix_alerta_produto_id'))
        batch_op.drop_index(batch_op.f('ix_alerta_destinatario_id'))
        batch_op.drop_index(batch_op.f('ix_alerta_data_criacao'))

    op.drop_table('alerta')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_setor'))
        batch_op.drop_index(batch_op.f('ix_produto_nome'))
        batch_op.drop_index(batch_op.f('ix_produto_ativo'))

    op.drop_table('produto')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_login'))

    op.drop_table('usuario')
    with op.batch_alter_table('dia_especial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dia_especial_data'))

    op.drop_table('dia_especial')
    # ### end Alembic commands ###

    for nome in _ENUMS:
        postgresql.ENUM(name=nome).drop(op.get_bind(), checkfirst=True)
