"""Trava de tentativas de login no usuario

Revision ID: 54fe0f0e2afb
Revises: 1aae989e9c24
Create Date: 2026-09-09 20:33:26.158012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fe0f0e2afb'
down_revision = '1aae989e9c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default e' obrigatorio aqui: sem ele, adicionar uma coluna NOT NULL
    # numa tabela que ja' tem usuarios cadastrados falha no banco de producao.
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tentativas_falhas', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_ate')
        batch_op.drop_column('tentativas_falhas')

    # ### end Alembic commands ###
